baseURL = "https://loadedartists.coding4.coffee"
languageCode = "en-us"
title = "LoadedArtists.com -- THE best place to read fully loaded LoadingArtist comics!"

[outputs]
section = ["HTML", "RSS", "JSON"]

[permalinks]
blog = "/:year/:month/:day/:filename/"
