baseURL = "https://loadedartists.coding4.coffee"
languageCode = "en-us"
title = "Loaded Artists"
enableRobotsTXT = true
paginate = 5

[params]
mainSections = ["comic"]
twitchApiHost = "https://loadedartists.coding4.coffee"

[imaging]
resampleFilter = "lanczos"
quality = 85

[outputs]
home = ["HTML", "RSS", "JSON"]

[permalinks]
news = "/:year/:month/:day/:filename/"
