baseURL = "https://loadedartists.coding4.coffee"
languageCode = "en-us"
title = "Loaded Artists"

[params]
cdnHost = "https://supertux88.github.io/loadedartists"

[outputs]
section = ["HTML", "RSS", "JSON"]

[permalinks]
news = "/:year/:month/:day/:filename/"
